# Generated by Django 6.0.3 on 2026-03-14 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, default='', max_length=300)),
                ('latitude', models.CharField(blank=True, default='', max_length=50)),
                ('longitude', models.CharField(blank=True, default='', max_length=50)),
                ('contact_number', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('hospital_type', models.CharField(choices=[('government', 'Government'), ('private', 'Private'), ('semi_govt', 'Semi-Government')], default='private', max_length=20)),
                ('total_beds', models.IntegerField(default=0)),
                ('available_beds', models.IntegerField(default=0)),
                ('specializations', models.TextField(blank=True, default='')),
                ('emergency_services', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
