# Generated by Django 6.0.3 on 2026-03-14 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='icu_beds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hospital',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('critical', 'Critical'), ('full', 'Full'), ('closed', 'Closed')], default='closed', max_length=20),
        ),
    ]
