# Generated by Django 6.0.3 on 2026-08-07 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0003_hospital_details_and_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hospitalstaff',
            options={'ordering': ['hospital__name', 'role', 'full_name'], 'verbose_name': 'Hospital Staff', 'verbose_name_plural': 'Hospital Staff'},
        ),
    ]
