# Generated by Django 6.0.3 on 2026-08-09 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0004_align_hospital_staff_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalstaff',
            name='banner_data',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='hospitalstaff',
            name='photo_data',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='hospitalstaff',
            name='years_experience',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hospitalstaff',
            name='role',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('nurse', 'Nurse'), ('technician', 'Technician'), ('support', 'Support Staff'), ('coordinator', 'Emergency Coordinator'), ('administrator', 'Administrator'), ('other', 'Other')], default='doctor', max_length=20),
        ),
    ]
