# Generated by Django 6.0.3 on 2026-09-19 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0007_seed_real_hospital_staff_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalstaff',
            name='assigned_booking_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospitalstaff',
            name='is_busy',
            field=models.BooleanField(default=False),
        ),
    ]
