# Generated by Django 6.0.3 on 2026-09-19 07:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0008_hospitalstaff_assigned_booking_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalBed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_number', models.CharField(db_index=True, max_length=50)),
                ('bed_type', models.CharField(choices=[('general', 'General'), ('icu', 'ICU')], default='general', max_length=20)),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('occupied', 'Occupied')], default='available', max_length=20)),
                ('wing', models.CharField(blank=True, default='General Ward • Wing B', max_length=80)),
                ('assigned_booking_id', models.IntegerField(blank=True, null=True)),
                ('patient_name', models.CharField(blank=True, default='', max_length=150)),
                ('patient_age', models.CharField(blank=True, default='', max_length=20)),
                ('patient_gender', models.CharField(blank=True, default='', max_length=20)),
                ('blood_group', models.CharField(blank=True, default='O-Negative (O-)', max_length=20)),
                ('patient_phone', models.CharField(blank=True, default='', max_length=30)),
                ('emergency_contact', models.CharField(blank=True, default='', max_length=200)),
                ('medical_condition', models.TextField(blank=True, default='')),
                ('vitals_summary', models.TextField(blank=True, default='')),
                ('attending_doctor', models.CharField(blank=True, default='', max_length=250)),
                ('assigned_staff_json', models.TextField(blank=True, default='[]')),
                ('admission_time', models.DateTimeField(blank=True, null=True)),
                ('last_status_update', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='hospitals.hospital')),
            ],
            options={
                'verbose_name': 'Hospital Bed',
                'verbose_name_plural': 'Hospital Beds',
                'ordering': ['bed_type', 'bed_number'],
            },
        ),
    ]
