# Generated by Django 6.0.3 on 2026-03-14 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambulance_id', models.IntegerField()),
                ('ambulance_number', models.CharField(blank=True, default='', max_length=50)),
                ('driver', models.CharField(blank=True, default='', max_length=100)),
                ('driver_contact', models.CharField(blank=True, default='', max_length=20)),
                ('booked_by', models.CharField(max_length=100)),
                ('booked_by_email', models.CharField(blank=True, default='', max_length=100)),
                ('pickup_location', models.CharField(max_length=300)),
                ('destination', models.CharField(blank=True, default='', max_length=300)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
    ]
