# Generated by Django 6.0.3 on 2026-08-07 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='assigned_hospital_address',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='booking',
            name='assigned_hospital_contact',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='assigned_hospital_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='booking',
            name='assigned_hospital_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='assigned_hospital_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='booking',
            name='attendant_contact',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='booking',
            name='attendant_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='booking',
            name='driver_modified_report',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='booking',
            name='driver_rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='driver_rejected_once',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='driver_rejection_reason',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='booking',
            name='driver_report_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='driver_task_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='driver_task_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='driver_voice_transcript',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='booking',
            name='hospital_alert_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='hospital_alert_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='hospital_assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='hospital_responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='hospital_response',
            field=models.CharField(blank=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='hospital_response_note',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='booking',
            name='insurance_dob',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='booking',
            name='insurance_emergency_nature',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='booking',
            name='insurance_exclusions_waiting',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='booking',
            name='insurance_full_name',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='booking',
            name='insurance_gender',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='booking',
            name='insurance_government_id',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='booking',
            name='insurance_hospital_note',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='booking',
            name='insurance_policy_holder_name',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='booking',
            name='insurance_policy_member_id',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='booking',
            name='insurance_provider',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='booking',
            name='insurance_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='insurance_reviewed_by',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='booking',
            name='insurance_status',
            field=models.CharField(blank=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='insurance_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='insurance_submitted_by',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='booking',
            name='insurance_sum_insured',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='booking',
            name='patient_age',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='patient_condition',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='booking',
            name='patient_contact_number',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='booking',
            name='patient_gender',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='patient_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='booking',
            name='pickup_city',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='booking',
            name='pickup_district',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='booking',
            name='pickup_landmark',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='booking',
            name='pickup_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='pickup_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='reassigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='reassigned_due_to_unavailability',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='report_sent_to_hospital',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='report_sent_to_hospital_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='report_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='report_submitted_by',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='booking',
            name='sent_to_driver',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='sent_to_driver_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='vitals_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='BookingChatThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(blank=True, default='', max_length=120)),
                ('user_name', models.CharField(blank=True, default='', max_length=120)),
                ('driver_email', models.CharField(blank=True, default='', max_length=120)),
                ('driver_name', models.CharField(blank=True, default='', max_length=120)),
                ('admin_email', models.CharField(blank=True, default='', max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('user_online', models.BooleanField(default=False)),
                ('driver_online', models.BooleanField(default=False)),
                ('admin_online', models.BooleanField(default=False)),
                ('user_typing', models.BooleanField(default=False)),
                ('driver_typing', models.BooleanField(default=False)),
                ('admin_typing', models.BooleanField(default=False)),
                ('user_last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('driver_last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('admin_last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_thread', to='bookings.booking')),
            ],
        ),
        migrations.CreateModel(
            name='BookingChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_role', models.CharField(choices=[('system', 'System'), ('admin', 'Admin'), ('driver', 'Driver'), ('user', 'User')], default='system', max_length=20)),
                ('sender_name', models.CharField(blank=True, default='', max_length=120)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('update', 'Update'), ('request', 'Request'), ('alert', 'Alert')], default='text', max_length=20)),
                ('message', models.TextField(blank=True, default='')),
                ('metadata', models.TextField(blank=True, default='')),
                ('seen_by_user', models.BooleanField(default=False)),
                ('seen_by_driver', models.BooleanField(default=False)),
                ('seen_by_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='bookings.bookingchatthread')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VoiceBookingCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_sid', models.CharField(db_index=True, max_length=120, unique=True)),
                ('from_number', models.CharField(blank=True, default='', max_length=30)),
                ('call_status', models.CharField(choices=[('ringing', 'Ringing'), ('in_progress', 'In Progress'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('failed', 'Failed'), ('ended', 'Ended')], default='ringing', max_length=20)),
                ('current_step', models.CharField(blank=True, default='name', max_length=30)),
                ('caller_name', models.CharField(blank=True, default='', max_length=120)),
                ('city', models.CharField(blank=True, default='', max_length=120)),
                ('district', models.CharField(blank=True, default='', max_length=120)),
                ('landmark', models.CharField(blank=True, default='', max_length=180)),
                ('attempts', models.IntegerField(default=0)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_calls', to='bookings.booking')),
            ],
        ),
    ]
