# Generated by Django 6.0.3 on 2026-09-17 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_workflow_chat_and_voice'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_user_selected_hospital',
            field=models.BooleanField(default=False),
        ),
    ]
