# Generated by Django 6.0.3 on 2026-09-17 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_is_user_selected_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='driver_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='driver_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='driver_status',
            field=models.CharField(blank=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='patient_reached',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='patient_reached_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
