# Generated by Django 6.0.3 on 2026-09-19 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_transfer_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='assigned_doctor_contacts',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='booking',
            name='assigned_doctor_names',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='booking',
            name='assigned_doctor_specializations',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='booking',
            name='assigned_doctors_json',
            field=models.TextField(blank=True, default='[]'),
        ),
        migrations.AddField(
            model_name='booking',
            name='doctors_assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
