# Generated by Django 6.0.3 on 2026-09-19 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_booking_assigned_doctor_contacts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='assigned_bed_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='assigned_bed_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='booking',
            name='assigned_bed_type',
            field=models.CharField(blank=True, default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='icu_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='icu_required',
            field=models.BooleanField(default=False),
        ),
    ]
