# Generated by Django 6.0.3 on 2026-09-20 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_patientconditionphoto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['-created_at'], name='bookings_bo_created_7d6386_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status'], name='bookings_bo_status_233e96_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['ambulance_id'], name='bookings_bo_ambulan_653d6d_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booked_by_email'], name='bookings_bo_booked__6c0296_idx'),
        ),
    ]
