# Generated by Django 6.0.3 on 2026-03-13 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambulance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulance',
            name='ambulance_number',
            field=models.CharField(default='AMB-0000', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ambulance',
            name='driver_contact',
            field=models.CharField(default='+91-0000000000', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ambulance',
            name='eta_to_hospital',
            field=models.CharField(default='0 km/h', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ambulance',
            name='eta_to_patient',
            field=models.CharField(default='0 min', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ambulance',
            name='hospital_distance',
            field=models.CharField(default='0 min', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ambulance',
            name='nearest_hospital',
            field=models.CharField(default='ABC 000000', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ambulance',
            name='speed',
            field=models.CharField(default='MBA 00000', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ambulance',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ambulance',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
