# Generated by Django 6.0.3 on 2026-03-13 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambulance', '0002_ambulance_ambulance_number_ambulance_driver_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulance',
            name='model',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='ambulance',
            name='ambulance_number',
            field=models.CharField(default='AMB-0000', max_length=50),
        ),
        migrations.AlterField(
            model_name='ambulance',
            name='driver_contact',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='ambulance',
            name='eta_to_hospital',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='ambulance',
            name='eta_to_patient',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='ambulance',
            name='hospital_distance',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='ambulance',
            name='nearest_hospital',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='ambulance',
            name='speed',
            field=models.CharField(blank=True, default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='ambulance',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('en_route', 'En Route'), ('busy', 'Busy'), ('offline', 'Offline')], default='offline', max_length=20),
        ),
    ]
