# Generated by Django 6.0.3 on 2026-03-14 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambulance', '0003_ambulance_model_alter_ambulance_ambulance_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulance',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ambulance',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='ambulance',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
    ]
