# Generated by Django 6.0.3 on 2026-03-14 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambulance', '0004_ambulance_last_updated_ambulance_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulance',
            name='driver_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='ambulance',
            name='ambulance_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ambulance',
            name='driver_contact',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='ambulance',
            name='eta_to_hospital',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='ambulance',
            name='eta_to_patient',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='ambulance',
            name='hospital_distance',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='ambulance',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ambulance',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='ambulance',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ambulance',
            name='model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ambulance',
            name='nearest_hospital',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='ambulance',
            name='speed',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
