# Generated by Django 6.0.3 on 2026-03-14 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambulance', '0006_driverlocation_suggestedroute'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestedroute',
            name='dest_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suggestedroute',
            name='dest_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suggestedroute',
            name='pickup_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suggestedroute',
            name='pickup_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
