# Generated by Django 6.0.3 on 2026-08-07 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambulance', '0007_suggestedroute_dest_lat_suggestedroute_dest_lng_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulance',
            name='ambulance_contract_id',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='ambulance',
            name='registration_number',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
