# Generated by Django 6.0.3 on 2026-09-13 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambulance', '0008_ambulance_ambulance_contract_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestedroute',
            name='booking_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
