# Generated by Django 6.0.3 on 2026-09-20 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambulance', '0009_add_booking_id_to_suggestedroute'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('role', models.CharField(choices=[('user', 'User'), ('driver', 'Driver'), ('hospital', 'Hospital'), ('staff', 'Staff'), ('admin', 'Admin')], db_index=True, default='user', max_length=20)),
                ('ambulance_id', models.IntegerField(blank=True, null=True)),
                ('ambulance_number', models.CharField(blank=True, default='', max_length=80)),
                ('contract_id', models.CharField(blank=True, default='', max_length=80)),
                ('registration_number', models.CharField(blank=True, default='', max_length=80)),
                ('hospital_id', models.IntegerField(blank=True, null=True)),
                ('hospital_name', models.CharField(blank=True, default='', max_length=200)),
                ('staff_id', models.CharField(blank=True, default='', max_length=80)),
                ('staff_role', models.CharField(blank=True, default='', max_length=80)),
                ('login_count', models.IntegerField(default=0)),
                ('first_login_at', models.DateTimeField(auto_now_add=True)),
                ('last_login_at', models.DateTimeField(auto_now=True)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ['-last_login_at'],
            },
        ),
        migrations.AddIndex(
            model_name='ambulance',
            index=models.Index(fields=['status'], name='ambulance_a_status_8cb0e8_idx'),
        ),
        migrations.AddIndex(
            model_name='ambulance',
            index=models.Index(fields=['driver_email'], name='ambulance_a_driver__23be76_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['role'], name='ambulance_u_role_e92a11_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['email'], name='ambulance_u_email_011ce8_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['-last_login_at'], name='ambulance_u_last_lo_cc3d47_idx'),
        ),
    ]
