# Generated by Django 6.0.3 on 2026-09-29 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ambulance', '0012_dispatch_query_indexes'),
        ('ambulance', '0012_tracking_state_and_routes'),
    ]

    operations = [
    ]
